name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: lab5_WAS/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: lab5_WAS

      - name: Run ESLint
        run: npm run lint
        working-directory: lab5_WAS

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: lab5_WAS/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: lab5_WAS

      - name: Run tests (ChromeHeadless)
        run: npm run test -- --watch=false --browsers=ChromeHeadless
        working-directory: lab5_WAS

  build:
    name: Build Angular App
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: lab5_WAS/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: lab5_WAS

      - name: Build the project
        run: npm run build -- --base-href=/lab5_WAS/
        working-directory: lab5_WAS

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: lab5_WAS/dist/lab5-was